### ISSUE TITLE
How does this compare to other ansible roles to configure globus?

### ISSUE THREAD

**Issue by zfrenchee** [EMBL-EBI-TSI/ansible-gridftp#1]
Particularly [this one](https://software.xsede.org/cb/centos6/noarch/extras/XCBC_Ansible/).

**Comment by luisico** [comment]
I guess this role is a general gridftp role, while the one you refer to seems tailored to XSEDE installations in clusters and in particular uses Globus. This role does not require Globus connection, and was designed to avoid Globus and get standalone gridftp networks.

The other piece that separates this role from XSEDE's and other gridftp roles out there is that it takes cares of gridftp servers and clients, certificate management and third-party utilities (fetch-crl and UberFTP). When combined with https://github.com/EMBL-EBI-TSI/ansible-simpleca you can also get a full gridftp network in vagrant machines with working (but not really secure) certificates. Take a look at this example playbook (https://github.com/EMBL-EBI-TSI/ansible-playbook-gridftp) for examples on how to fully leverage ansible-gridftp and andsible-simpleca roles.

Having said that, we are also working in add optional globus connection to this role.

**Comment by zfrenchee** [comment]
Interesting -- why was this designed to avoid globus? And when will you add globus connection to this role?

**Comment by luisico** [comment]
Just a requirement of the project that I'm working at.

No ETA as of yet for globus
