### ISSUE TITLE
Have you considered using secure gridftp? 

### ISSUE THREAD

**Issue by zfrenchee** [EMBL-EBI-TSI/ansible-gridftp#2]
http://toolkit.globus.org/toolkit/docs/latest-stable/gridftp/admin/#gridftp-admin-config-security-sshftp

**Comment by luisico** [comment]
Not really. Some colleges here are using sshftp as their gridftp protocol for testing purposes, but we found that it was not performant compared to gsiftp (this was an observation, not a comprehensive benchmark, though). Sure sshftp is easier to install without all this certificate madness, but this is actually the problem that this role is suppose to solve: certificate management.

I'm not against adding sshftp to this role, but don't have the time right now. I welcome pull requests, though ;-)
